name = "dev-tools"
type = "webpack"
account_id = ""
route = ""
zone_id = ""
usage_model = ""
workers_dev = true

[site]
bucket = "./dist"
entry-point = "workers-site"

[build]
command = "npm run build"
publish = "dist"